version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist:/app/dist
    restart: unless-stopped
    command: bun run serve -s dist -l 3000
